type-a:
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: m4.large
    boot_disk_size: 40
    image_id: ami-085925f297f89fce1
    security_group: mpi_group
       
# type-b:
#     provider: aws-config-us-east-1
#     login: login-ubuntu-b
#     flavor: t2.small
#     image_id: ami-07d0cf3af28718ef8
#     boot_disk_size: 10
    # image_userdata: 
    # boot_disk_device: /dev/sda1
    # boot_disk_iops: io1
    # boot_disk_type: gp2
    # placement_group: XXX
