type-compiler:
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: m4.large
    boot_disk_size: 40
    image_id: ami-085925f297f89fce1
    security_group: mpi_group
       
type-processor:
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: t2.small
    boot_disk_size: 40
    image_id: ami-085925f297f89fce1
    security_group: mpi_group