type-compiler: # 0,252 USD por hora
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: r5.2xlarge
    boot_disk_size: 40
    image_id: ami-085925f297f89fce1
    security_group: mpi_group


type-processor-a: # 0,023 USD por hora
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: t2.small
    boot_disk_size: 40
    image_id: ami-085925f297f89fce1
    security_group: mpi_group


type-processor-b: # 0,0208 USD por hora
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: t3.small
    boot_disk_size: 40
    image_id: ami-085925f297f89fce1
    security_group: mpi_group


type-processor-c: # 0,1664 USD por hora
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: t3.xlarge
    boot_disk_size: 40
    image_id: ami-085925f297f89fce1
    security_group: mpi_group


type-processor-d: # 0,17 USD por hora
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: c5.xlarge
    boot_disk_size: 40
    image_id: ami-085925f297f89fce1
    security_group: mpi_group
    placement_group: opm_cluster_placement_group