---
- hosts: all
  gather_facts: no
  tasks:
  - name: Gera ssh
    shell: "ssh-keygen -N '' -f ~/.ssh/id_rsa"
  - name: Pegar arquivo ssh do host
    become: no
    synchronize:
      src: ~/.ssh/id_rsa.pub
      dest: /home/matheus/Desktop/mo833/ativ7/teste/{{inventory_hostname}}-id_rsa.pub
      mode: pull
      recursive: yes
  - name: faz pasta pros sshs
    shell: "mkdir sshs_amigas"
  - name: Fazendo upload ssh keys
    become: no
    synchronize:
      src: /home/matheus/Desktop/mo833/ativ7/teste/
      dest: ~/sshs_amigas/
      recursive: yes
  - name: Pegando script setup2
    become: no
    shell: "cd ~/sshs_amigas/ && wget https://raw.githubusercontent.com/MatheusFerraroni/gromacs-mo833a/ativi-7-exp-1/experiments/ativ-7-exp-1/script_setup2.sh && sh script_setup2.sh"
  - name: Remove hosts file
    file:
      path: /home/ubuntu/hosts
      state: absent
  - name: Create hosts file
    file:
      path: /home/ubuntu/hosts
      state: touch
  - name: Add Ansible inventory mappings to /home/ubuntu/hosts
    blockinfile:
      marker: ""
      path: /home/ubuntu/hosts
      block: |
        {% for host in groups['all'] %}
        {{ hostvars[host].ansible_host }} slots=1
        {% endfor %}
  - name: Remove ips file
    file:
      path: ~/ips.sh
      state: absent
  - name: Create ips file
    file:
      path: ~/ips.sh
      state: touch
  - name: Add Ansible inventory mappings to ~/ips.sh
    blockinfile:
      marker: ""
      path: ~/ips.sh
      block: |
        {% for host in groups['all'] %}
        ssh-keyscan -H {{ hostvars[host].ansible_host }} >> ./.ssh/known_hosts
        {% endfor %}
  - name: Executa ips.sh
    shell: "sh ips.sh"