---
- hosts: all
  tasks:
    
  - name: "print montando efs"
    debug:
      msg: "mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport {{ efslocation }} /home/ubuntu/efs"
  - name: MONTA EFS
    become: yes
    shell: "mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport {{ efslocation }} /home/ubuntu/efs"
