---
- hosts: all
  tasks:




  - name: Executando NORNE
    shell: /usr/bin/time -p -o /home/ubuntu/resultados/tempos_real.txt mpirun -hostfile /home/ubuntu/hosts /home/ubuntu/efs/opm-simulators/build/bin/flow --max-pi={{maxpi}} NORNE_ATW2013.DATA | grep -e MO833 > /home/ubuntu/resultados/tempos.txt
    args:
      chdir: /home/ubuntu/opm-data/norne
  - name: Preparando tempos
    shell: cat tempos_real.txt | grep real | sed 's/ /,/g' >> tempos.txt && rm tempos_real.txt
    args:
      chdir: /home/ubuntu/resultados/
  - name: Pegando Norne Results
    become: no
    synchronize:
      src: /home/ubuntu/resultados/tempos.txt
      dest: ~/experimental_results/NORNE/{{tipo}}/{{ ansible_date_time.date }} {{ ansible_date_time.time }}.txt
      mode: pull
      recursive: yes

  - name: Executando spe10model1
    shell: /usr/bin/time -p -o /home/ubuntu/resultados/tempos_real.txt mpirun -hostfile /home/ubuntu/hosts /home/ubuntu/efs/opm-simulators/build/bin/flow --max-pi={{maxpi}} SPE10_MODEL1.DATA | grep -e MO833 > /home/ubuntu/resultados/tempos.txt
    args:
      chdir: /home/ubuntu/opm-data/spe10model1
  - name: Preparando tempos
    shell: cat tempos_real.txt | grep real | sed 's/ /,/g' >> tempos.txt && rm tempos_real.txt
    args:
      chdir: /home/ubuntu/resultados/
  - name: Pegando spe10model1 Results
    become: no
    synchronize:
      src: /home/ubuntu/resultados/tempos.txt
      dest: ~/experimental_results/spe10model1/{{tipo}}/{{ ansible_date_time.date }} {{ ansible_date_time.time }}.txt
      mode: pull
      recursive: yes

  - name: Executando spe9
    shell: /usr/bin/time -p -o /home/ubuntu/resultados/tempos_real.txt mpirun -hostfile /home/ubuntu/hosts /home/ubuntu/efs/opm-simulators/build/bin/flow --max-pi={{maxpi}} SPE9.DATA | grep -e MO833 > /home/ubuntu/resultados/tempos.txt
    args:
      chdir: /home/ubuntu/opm-data/spe9
  - name: Preparando tempos
    shell: cat tempos_real.txt | grep real | sed 's/ /,/g' >> tempos.txt && rm tempos_real.txt
    args:
      chdir: /home/ubuntu/resultados/
  - name: Pegando spe9 Results
    become: no
    synchronize:
      src: /home/ubuntu/resultados/tempos.txt
      dest: ~/experimental_results/spe9/{{tipo}}/{{ ansible_date_time.date }} {{ ansible_date_time.time }}.txt
      mode: pull
      recursive: yes





