---

- name: "Security group playbook"
  hosts: localhost 
  gather_facts: false
  tasks:
  - name: "Create security group in ec2 us-east-1"
    ec2_group:
      aws_secret_key: "{{lookup('file', '~/.clap/private/clapp_key.pem') }}"
      aws_access_key: "{{lookup('file', '~/.clap/private/clapp_acess.pub') }}"
      region: "us-east-1"
      name: "mpi_mo833_ra212142"
      description: "An example EC2 group"
      state: "present"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: all
        group_name: mpi_mo833_ra212142
    register: "resultado_da_criacao"
    
  - name: "Print creation results dictionary"
    debug:
      msg: "vpc={{ resultado_da_criacao.vpc_id }}"
    
  - name: "Print creation results dictionary"
    debug:
      msg: "group={{ resultado_da_criacao.group_id }}"
    
  - name: "Print creation results dictionary"
    debug:
      msg: "teste"
  - name: "Print creation results dictionary"
    debug:
      msg: "teste2"