---
- hosts: all
  tasks:
  - name: Debug task....
    debug:
      msg: OPM setup action called! 
  - name: Configurando pacotes e clonando OPM
    become: yes
    shell: "wget https://raw.githubusercontent.com/MatheusFerraroni/opm-mo833/master/scripts/setup1.sh && sh setup1.sh"
  - name: MONTA EFS
    become: yes
    shell: "mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-2e5fb0ad.efs.us-east-1.amazonaws.com:/ /home/ubuntu/efs"
  - name: Coloca 777 na pasta do opm-* no /home/ubuntu/
    become: yes
    shell: "chmod -R 777 /home/ubuntu/opm-*/"



  - name: Checa se opm-common ja foi compilado
    stat:
      path: /home/ubuntu/efs/opm-common/build/bin
    register: stat_result
  - name: CMAKE opm-common
    shell: cmake .. -DUSE_MPI=1 1> cmake.out 2> cmake.outerr
    args:
      chdir: /home/ubuntu/opm-common/build
    when: not stat_result.stat.exists
  - name: MAKE opm-common
    shell: make -i -j 2 1> make_res.out 2> make_res.outerr
    async: 18000
    poll: 0
    register: commonjob
    args:
      chdir: /home/ubuntu/opm-common/build
    when: not stat_result.stat.exists
  - name: ESPERANDO commonjob
    async_status:
      jid: "{{ commonjob.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    when: not stat_result.stat.exists
    retries: 30000



  - name: Checa se opm-material ja foi compilado
    stat:
      path: /home/ubuntu/efs/opm-material/build/bin
    register: stat_result
  - name: CMAKE opm-material
    shell: cmake .. -DUSE_MPI=1 1> cmake.out 2> cmake.outerr
    args:
      chdir: /home/ubuntu/opm-material/build
    when: not stat_result.stat.exists
  - name: MAKE opm-material
    shell: make -j 2 1> make_res.out 2> make_res.outerr
    async: 18000
    poll: 0
    register: materialjob
    args:
      chdir: /home/ubuntu/opm-material/build
    when: not stat_result.stat.exists
  - name: 'ESPERANDO materialjob'
    async_status:
      jid: "{{ materialjob.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    when: not stat_result.stat.exists
    retries: 30000



  - name: Checa se opm-grid ja foi compilado
    stat:
      path: /home/ubuntu/efs/opm-grid/build/bin
    register: stat_result
  - name: CMAKE opm-grid
    shell: cmake .. -DUSE_MPI=1 1> cmake.out 2> cmake.outerr
    args:
      chdir: /home/ubuntu/opm-grid/build
    when: not stat_result.stat.exists
  - name: MAKE opm-grid
    shell: make -j 2 1> make_res.out 2> make_res.outerr
    async: 18000
    poll: 0
    register: gridjob
    args:
      chdir: /home/ubuntu/opm-grid/build
    when: not stat_result.stat.exists
  - name: 'ESPERANDO gridjob'
    async_status:
      jid: "{{ gridjob.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    when: not stat_result.stat.exists
    retries: 30000


  - name: Checa se opm-models ja foi compilado
    stat:
      path: /home/ubuntu/efs/opm-models/build/bin
    register: stat_result
  - name: CMAKE opm-models
    shell: cmake .. -DUSE_MPI=1 1> cmake.out 2> cmake.outerr
    args:
      chdir: /home/ubuntu/opm-models/build
    when: not stat_result.stat.exists
  - name: MAKE opm-models
    shell: make -j 2 1> make_res.out 2> make_res.outerr
    async: 18000
    poll: 0
    register: modelsjob
    args:
      chdir: /home/ubuntu/opm-models/build
    when: not stat_result.stat.exists
  - name: 'ESPERANDO modelsjob'
    async_status:
      jid: "{{ modelsjob.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    when: not stat_result.stat.exists
    retries: 30000


  - name: Checa se opm-simulators ja foi compilado
    stat:
      path: /home/ubuntu/efs/opm-simulators/build/bin
    register: stat_result
  - name: CMAKE opm-simulators
    shell: cmake .. -DUSE_MPI=1 1> cmake.out 2> cmake.outerr
    args:
      chdir: /home/ubuntu/opm-simulators/build
    when: not stat_result.stat.exists
  - name: MAKE opm-simulators
    shell: make 1> make_res.out 2> make_res.outerr
    async: 18000
    poll: 0
    register: simulatorsjob
    args:
      chdir: /home/ubuntu/opm-simulators/build
    when: not stat_result.stat.exists
  - name: 'ESPERANDO simulatorsjob'
    async_status:
      jid: "{{ simulatorsjob.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    when: not stat_result.stat.exists
    retries: 30000



  - name: Checa se opm-upscaling ja foi compilado
    stat:
      path: /home/ubuntu/efs/opm-upscaling/build/bin
    register: stat_result
  - name: CMAKE opm-upscaling
    shell: cmake .. -DUSE_MPI=1 1> cmake.out 2> cmake.outerr
    args:
      chdir: /home/ubuntu/opm-upscaling/build
    when: not stat_result.stat.exists
  - name: MAKE opm-upscaling
    shell: make -j 2 1> make_res.out 2> make_res.outerr
    async: 18000
    poll: 0
    register: upscalingjob
    args:
      chdir: /home/ubuntu/opm-upscaling/build
    when: not stat_result.stat.exists
  - name: 'ESPERANDO upscaling'
    async_status:
      jid: "{{ upscalingjob.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    when: not stat_result.stat.exists
    retries: 30000

  - name: Coloca 777 na pasta do opm-*
    become: yes
    shell: "chmod -R 777 /home/ubuntu/opm-*/"
  

  - name: Checa se opm-common ja foi para o efs
    stat:
      path: /home/ubuntu/efs/opm-common
    register: stat_result
  - name: Coloca opm-common no efs se necessario
    become: yes
    shell: "cp -r /home/ubuntu/opm-common /home/ubuntu/efs/opm-common"
    when: not stat_result.stat.exists

  - name: Checa se opm-material ja foi para o efs
    stat:
      path: /home/ubuntu/efs/opm-material
    register: stat_result
  - name: Coloca opm-material no efs se necessario
    become: yes
    shell: "cp -r /home/ubuntu/opm-material /home/ubuntu/efs/opm-material"
    when: not stat_result.stat.exists

  - name: Checa se opm-grid ja foi para o efs
    stat:
      path: /home/ubuntu/efs/opm-grid
    register: stat_result
  - name: Coloca opm-grid no efs se necessario
    become: yes
    shell: "cp -r /home/ubuntu/opm-grid /home/ubuntu/efs/opm-grid"
    when: not stat_result.stat.exists

  - name: Checa se opm-models ja foi para o efs
    stat:
      path: /home/ubuntu/efs/opm-models
    register: stat_result
  - name: Coloca opm-models no efs se necessario
    become: yes
    shell: "cp -r /home/ubuntu/opm-models /home/ubuntu/efs/opm-models"
    when: not stat_result.stat.exists

  - name: Checa se opm-simulators ja foi para o efs
    stat:
      path: /home/ubuntu/efs/opm-simulators
    register: stat_result
  - name: Coloca opm-simulators no efs se necessario
    become: yes
    shell: "cp -r /home/ubuntu/opm-simulators /home/ubuntu/efs/opm-simulators"
    when: not stat_result.stat.exists

  - name: Checa se opm-upscaling ja foi para o efs
    stat:
      path: /home/ubuntu/efs/opm-upscaling
    register: stat_result
  - name: Coloca opm-upscaling no efs se necessario
    become: yes
    shell: "cp -r /home/ubuntu/opm-upscaling /home/ubuntu/efs/opm-upscaling"
    when: not stat_result.stat.exists


  - name: Coloca 777 na pasta do opm-* no EFS
    become: yes
    shell: "chmod -R 777 /home/ubuntu/efs/opm-*/"