---
- hosts: all
  tasks:



  - name: Executando NORNE PERF
    shell: /home/ubuntu/efs/opm-simulators/build/bin/flow NORNE_ATW2013.DATA > out.txt
    async: 18000
    poll: 0
    register: runningnorne
    args:
      chdir: /home/ubuntu/opm-data/norne

  - name: 'Esperando runningnorne'
    async_status:
      jid: "{{ runningnorne.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 30000




# cd /home/ubuntu/opm-data/spe10model1
# /home/ubuntu/opm-simulators/build/bin/flow SPE10_MODEL1.DATA

# cd /home/ubuntu/opm-data/spe9
# /home/ubuntu/opm-simulators/build/bin/flow SPE9.DATA
