---
- hosts: all
  tasks:
  - name: Instalando dependencias do EFS
    become: yes
    shell: "wget https://raw.githubusercontent.com/MatheusFerraroni/opm-mo833/master/scripts/prepara_efs.sh && sh prepara_efs.sh"