---
- hosts: all
  tasks:
  - name: Instalando dependencias do EFS
    become: yes
    shell: "wget https://raw.githubusercontent.com/MatheusFerraroni/opm-mo833/master/scripts/prepara_efs.sh && sh prepara_efs.sh"
  - name: MONTA EFS
    become: yes
    shell: "mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-2e5fb0ad.efs.us-east-1.amazonaws.com:/ /home/ubuntu/efs"
