---

- name: "Deleta efs, security group e placement group"
  hosts: localhost 
  gather_facts: false
  tasks:
  - name: "delete placement Group"
    ec2_placement_group:
      aws_secret_key: "{{lookup('file', '~/.clap/private/clapp_key.pem') }}"
      aws_access_key: "{{lookup('file', '~/.clap/private/clapp_acess.pub') }}"
      region: "us-east-1"
      name: "opm_mo833_212142"
      state: absent
    register: "resultado_da_criacao"
    
  - name: "Print creation results dictionary"
    debug:
      msg: "{{ resultado_da_criacao }}"

  - name: "Deleta EFS"
    efs:
      aws_secret_key: "{{lookup('file', '~/.clap/private/clapp_key.pem') }}"
      aws_access_key: "{{lookup('file', '~/.clap/private/clapp_acess.pub') }}"
      region: "us-east-1"
      name: efs_mo833_ra212142
      state: absent
    register: "resultado_da_criacao"
    
  - name: "Print creation results dictionary"
    debug:
      msg: "{{ resultado_da_criacao }}"

  - name: "Deleta security group"
    ec2_group:
      aws_secret_key: "{{lookup('file', '~/.clap/private/clapp_key.pem') }}"
      aws_access_key: "{{lookup('file', '~/.clap/private/clapp_acess.pub') }}"
      region: "us-east-1"
      name: "mpi_mo833_ra212142"
      state: absent
    register: "resultado_da_criacao"
    
  - name: "Print creation results dictionary"
    debug:
      msg: "{{ resultado_da_criacao }}"