setups:
  config-omp-t2small-1-master:
    groups:
    - name: opm
    actions:
    - type: command
      command: touch master.txt

  prepara-tudo:
    actions:
    - type: action
      name: hosts
      group: opm


clusters:
  cluster-opm-t2small-1:
    nodes:
      node-master:
        type: type-processor-a
        count: 1
        min_count: 1
        setups: 
        - config-omp-t2small-1-master


    after_all:
    - prepara-tudo