setups:
  config-compiler:
    groups:
    - name: opm



clusters:
  cluster-opm-compiler:
    nodes:
      node-master:
        type: type-compiler
        count: 1
        min_count: 1
        setups: 
        - config-compiler