setups:
  config-master-opm-1:
    groups:
    - name: opm
    actions:
    - type: command
      command: touch master.txt


clusters:
  cluster-opm:
    nodes:
      node-master:
        type: type-compiler
        count: 1
        min_count: 1
        setups: 
        - config-master-opm-1