setups:
  config-compiler:
    groups:
    - name: opm
    actions:
    - type: action
      name: compila
      group: opm


clusters:
  cluster-opm-compiler:
    nodes:
      node-master:
        type: type-compiler
        count: 1
        min_count: 1
        setups: 
        - config-compiler